ALTER TABLE coffees
  ALTER COLUMN cultivar TYPE TEXT[]
  USING CASE WHEN cultivar IS NULL THEN ARRAY[]::TEXT[] ELSE ARRAY[cultivar] END;

ALTER TABLE coffees ALTER COLUMN cultivar SET DEFAULT '{}';
ALTER TABLE coffees ALTER COLUMN cultivar SET NOT NULL;
